/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.internalFrame;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Ciclo;
import modelsDao.ManagerDaoImpl;

/**
 *
 * @author JMARSER
 */
public class Ciclos extends javax.swing.JInternalFrame {

    private ManagerDaoImpl gestor = new ManagerDaoImpl();
    
    //modelo para la tabla
    private DefaultTableModel modelo_tabla = new DefaultTableModel();
    private List<Ciclo> listadoCiclos = new ArrayList<>();
    
    //variable estática con la que controlamos que sólo se pueda instanciar una ventana de este clase
    public static String x;
   
    public Ciclos() {
        initComponents();
        this.x = "x";
        initVentana();
    }
    
    private void initVentana(){
        this.setTitle("GESTIÓN DE CICLOS");
        initTabla();
        mostrarCiclos();
    }
    
    private void initTabla(){
        modelo_tabla.addColumn("Id");
        modelo_tabla.addColumn("Nombre ciclo");
        this.jt_listaCiclos.setModel(modelo_tabla);
    }

    private void mostrarCiclos(){
        limpiarTabla();
        listadoCiclos = (ArrayList<Ciclo>)gestor.getCicloDao().getAll();
        
        Object[] linea = new Object[modelo_tabla.getColumnCount()];
        
        if(listadoCiclos != null){
            for(int i = 0; i<listadoCiclos.size(); i++){
                linea[0] = listadoCiclos.get(i).getId();
                linea[1] = listadoCiclos.get(i).getNombre();
                
                modelo_tabla.addRow(linea);
            }
        }
    }
    
    private void addCiclo(){
        if(validarCampos()){
            Ciclo ciclo = new Ciclo();
            ciclo.setNombre(this.jtf_nuevoCiclo.getText());
            
            gestor.getCicloDao().insert(ciclo);
        }
        limpiarCampo();
        mostrarCiclos();
    }
    
    private boolean validarCampos(){
        if(!this.jtf_nuevoCiclo.getText().isEmpty()){
            return true;
        }else{
            return false;
        }
    }
    
    private void limpiarCampo(){
        this.jtf_nuevoCiclo.setText("");
    }
    
    /*método con el que limpiamos la tabla*/
    private void limpiarTabla(){
        modelo_tabla.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listaCiclos = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_nuevoCiclo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jt_listaCiclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_listaCiclos);

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevo ciclo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtf_nuevoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guardar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nuevoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        addCiclo();
    }//GEN-LAST:event_btn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_listaCiclos;
    private javax.swing.JTextField jtf_nuevoCiclo;
    // End of variables declaration//GEN-END:variables
}
