/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.internalFrame;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import models.Empresa;
import modelsDao.ManagerDaoImpl;

/**
 *
 * @author JMARSER
 */
public class Empresas extends javax.swing.JInternalFrame {

    private ManagerDaoImpl gestor = new ManagerDaoImpl();

    //modelo para la tabla
    private DefaultTableModel modelo_tabla = new DefaultTableModel();
    private List<Empresa> listadoEmpresas = new ArrayList<>();

    //variable estática con la que controlamos que sólo se pueda instanciar una ventana de este clase
    public static String x;

    public Empresas() {
        initComponents();
        this.x = "x";
        initVentana();
    }

    /*Iniciamos algunas características de la ventana*/
    private void initVentana() {
        this.setTitle("GESTIÓN DE EMPRESAS");
        initTabla();
        mostrarEmpresas();
    }

    /*Damos estilo a la tabla y nombramos sus columnas*/
    private void initTabla() {
        modelo_tabla.addColumn("Id");
        modelo_tabla.addColumn("Empresa");
        this.jt_listaEmpresas.setModel(modelo_tabla);
        
        //determinamos el ancho de las columnas
        this.jt_listaEmpresas.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.jt_listaEmpresas.getColumnModel().getColumn(1).setPreferredWidth(300);
        
        //centramos el contenido de las celdas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        this.jt_listaEmpresas.getColumnModel().getColumn(0).setCellRenderer(tcr);
        this.jt_listaEmpresas.getColumnModel().getColumn(1).setCellRenderer(tcr);
        
        /*Para el centrado del contenido de la cabecera necesitamos instanciar 
        otra clase*/
        JTableHeader th = this.jt_listaEmpresas.getTableHeader();
        th.setDefaultRenderer(tcr);
        this.jt_listaEmpresas.setTableHeader(th);
    }

    /*Obtenemos las empresas que hay guardadas en la base de datos y las cargamas
    en el JComboBox correspondiente*/
    private void mostrarEmpresas() {
        limpiarTabla();
        listadoEmpresas = (ArrayList<Empresa>) gestor.getEmpresaDao().getAll();

        Object[] linea = new Object[modelo_tabla.getColumnCount()];

        if (listadoEmpresas != null) {
            for (int i = 0; i < listadoEmpresas.size(); i++) {
                linea[0] = listadoEmpresas.get(i).getId();
                linea[1] = listadoEmpresas.get(i).getNombre();

                modelo_tabla.addRow(linea);
            }
        }
    }

    /*Método con el que solicitamos guardar una nueva empresa en la base de datos*/
    private void addEmpresa() {
        if (validarCampos()) {
            Empresa emp = new Empresa();
            emp.setNombre(this.jtf_nuevaEmpresa.getText());

            if (gestor.getEmpresaDao().insert(emp)) {
                JOptionPane.showMessageDialog(null, "Empresa insertada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar la empresa.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre para la empresa.");
        }
        limpiarCampos();
        mostrarEmpresas();
    }

    private void limpiarCampos() {
        this.jtf_nuevaEmpresa.setText("");
    }

    /*método con el que limpiamos la tabla*/
    private void limpiarTabla() {
        modelo_tabla.setRowCount(0);
    }

    private boolean validarCampos() {
        if (!this.jtf_nuevaEmpresa.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listaEmpresas = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_nuevaEmpresa = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jt_listaEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_listaEmpresas);

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nueva empresa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtf_nuevaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guardar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nuevaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        addEmpresa();
    }//GEN-LAST:event_btn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_listaEmpresas;
    private javax.swing.JTextField jtf_nuevaEmpresa;
    // End of variables declaration//GEN-END:variables
}
